.TH tim 1
.SH NAME
.PP
tim  \- extendable personal assistant
.SH SYNOPSIS
.PP
\fB\fCtim\fR [\fB\-iv\fP] [\fBCMD\fP]
.SH DESCRIPTION
.PP
Tim is a light weight personal assistant that is extendable with lua and JSON.
.SH OPTIONS
.PP
\fB\-i\fP [\fICMD\fP]
    Enable interactive mode, more commands can be given though stdin after
    last one was read and answer outputted
.PP
\fB\-v\fP
    Print version info and exit
.SH COMMANDS
.SH AUTHOR
.PP
Ed van Bruggen 
\<edvb54@gmail.com\>
.SH SEE ALSO
.PP
View source code at: 
\<https://gitlab.com/edvb/tim\>
.SH LICENSE
.PP
zlib License
